name: Packer Build after Merge

on:
  [pull_request]

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read 

jobs:
  Run-Packer-Build-Check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/checkout@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Artifact Setup
        if: success()
        run: zip -r webapp.zip .

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.ACCESS_KEY}}
          role-session-name: AWS Session 
          aws-region: us-east-1

      - name: Initialization
        run:
          cd packer
          packer init aws.pkr.hcl

      - name: Build AMI
        run:
          cd packer
          packer build aws.pkr.hcl






