name: Healthz CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Run-Integration-test-for-healthz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up postgres
        run: |

          source .env
          
          sudo apt-get update
          sudo apt-get install postgresql
          sudo service postgresql start
                    
          
          # Change the user's password using superuser privileges
          sudo -u postgres psql -c "ALTER USER ${{secrets.DATABASE_USER}} WITH PASSWORD '${{secrets.DATABASE_PASS}}';"

      - name: Use Node.js 18v
        uses: actions/setup-node@v3
        with:
            node-version: 18.x
            cache: 'npm'

      - name: Set .env file
        run: |
          echo DATABASE_USER="${{secrets.DATABASE_USER}}" >> .env
          echo DATABASE_PASS="${{secrets.DATABASE_PASS}}" >> .env
          echo DATABASE="${{secrets.DATABASE}}" >> .env
          echo DATABASE_HOST="${{secrets.DATABASE_HOST}}" >> .env
          echo DATABASE_PORT="${{secrets.DATABASE_PORT}}" >> .env
          echo DIALECT="${{secrets.DIALECT}}" >> .env
          echo DEFAULTUSERSPATH="" >> .env

      - name: Run Integration Test
        run: |
            ls -A
            npm i -force
            npm run test