name: Healthz CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Run-Integration-test-for-healthz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set .env file
        run: |
          touch .env
          echo "DATABASE_PASS=${{secrets.DATABASE_PASS}}" >> .env
          echo "DATABASE=${{secrets.DATABASE}}" >> .env
          echo "DATABASE_USER=${{secrets.DATABASE_USER}}" >> .env
          echo "DATABASE_PORT=${{secrets.DATABASE_PORT}}" >> .env
          echo "DATABASE_HOST=${{secrets.DATABASE_HOST}}" >> .env
          echo "DIALECT=${{secrets.DIALECT}}" >> .env
          echo "DEFAULTUSERSPATH="" "  >> .env


      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-client
          sudo service postgresql start
          pg_isready

      - name: Install Dependencies
        run: npm install

      - name: Create PG user and connect
        run: |
          # Load environment variables from .env file
          source .env
          
          # Change the user's password using superuser privileges
          sudo -u postgres psql -c "ALTER USER ${{secrets.DATABASE_USER}} WITH PASSWORD '${{secrets.DATABASE_PASS}} ';"
          
          # Connect to the 'postgres' database using the specified user and password
          PGPASSWORD=${{secrets.DATABASE_PASS}}  psql -U ${{secrets.DATABASE_USER}} -h '${{secrets.DATABASE_HOST}}' -p ${{secrets.DATABASE_PORT}}

      - name: Run Integration Tests
        run: |
          # Load environment variables from .env file
          source .env

          # Run integration tests using environment variables
          npm run test
